version: "3.7"

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: /usr/local/sbin/php-fpm -F

  pgsql:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: dibby
      POSTGRES_USER: dibby
      POSTGRES_DB: dibby
    volumes:
      - "pgsql:/var/lib/postgresql/data"

  mailhog:
    image: cd2team/mailhog
    environment:
      MH_MAILDIR_PATH: /maildir
      MH_STORAGE: maildir
    ports:
      - "8025:8025"
    volumes:
      - "mailhog:/maildir"

volumes:

  pgsql:

  mailhog:
