version: "3.7"

services:

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8001:80"
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/50_xdebug.ini
      - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/99_overrides.ini
    entrypoint: /usr/local/sbin/php-fpm -F

  pgsql:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: dibby
      POSTGRES_USER: dibby
      POSTGRES_DB: dibby
    working_dir: /app
    volumes:
      - .:/app
      - "pgsql:/var/lib/postgresql/data"

  mailhog:
    image: cd2team/mailhog
    environment:
      MH_MAILDIR_PATH: /maildir
      MH_STORAGE: maildir
    ports:
      - "8002:8025"
    volumes:
      - "mailhog:/maildir"

volumes:

  pgsql:

  mailhog:
