version: "3.8"

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - .:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: .env
    depends_on:
      - php

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app:ro
    env_file: .env
    entrypoint: /usr/local/sbin/php-fpm -F
    depends_on:
      - pgsql

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env

  pgsql:
    image: postgres:14-alpine
    volumes:
      - "pgsql:$PGDATA"
    env_file: .env

volumes:

  pgsql:
