version: "3.8"

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: /usr/local/sbin/php-fpm -F

  pgsql:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: dibby
      POSTGRES_USER: dibby
      POSTGRES_DB: dibby
    volumes:
      - "pgsql:/var/lib/postgresql/data"

volumes:

  pgsql:
