version: "3.8"

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/php
    working_dir: /app
    volumes:
      - .:/app:ro
    entrypoint: /usr/local/sbin/php-fpm -F
    depends_on:
      - pgsql

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app

  pgsql:
    image: postgres:14-alpine
    volumes:
      - "pgsql:/var/lib/postgresql/data"

volumes:

  pgsql:
